-- Create the 'orders' table
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id), -- Nullable for guest checkout
    total_amount NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'Order Received',
    payment_method TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    city TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create the 'order_items' table
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL, -- Assuming product IDs are strings based on CartItem interface
    quantity INTEGER NOT NULL,
    price NUMERIC NOT NULL
);

-- Re-run policies just in case (Idempotent if policies already exist, but good to ensure coverage)
-- (Note: 'create policy' might fail if it already exists, so we wrap in a DO block or just assume user ran the previous file. 
-- For simplicity, let's keep this file focused on Table Creation. The user already ran the policies.)
