-- DANGER: This will delete existing order data!
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;

-- Create the 'orders' table (Correct Schema)
CREATE TABLE public.orders (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    total_amount NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'Order Received',
    payment_method TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    city TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create the 'order_items' table
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC NOT NULL
);

-- Re-enable RLS
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Re-apply policies (Simpler version)
CREATE POLICY "Public Insert Orders" ON orders FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "User View Orders" ON orders FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Public Insert Items" ON order_items FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "User View Items" ON order_items FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
);
