'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        'home': 'Home',
        'products': 'Products',
        'about': 'About',
        'contact': 'Contact',
        'cart': 'Cart',
        'search': 'Search',
        'admin': 'Admin',
        'login': 'Login',
        'logout': 'Logout',
        'my_profile': 'My Profile',
        'total': 'Total',
        'checkout': 'Checkout',
        'proceed_to_checkout': 'Proceed to Checkout',
        'cash_notice': 'Cash on Delivery Only. Card payment coming soon.',
        'trending': 'Trending Now',
        'view_all': 'View All',
        'points': 'Loyalty Points',
        'dashboard': 'Dashboard',
        'orders': 'Orders',
        'my_orders': 'My Orders',
        'account_settings': 'Account Settings',
        'full_name': 'Full Name',
        'email_address': 'Email Address',
        'phone_number': 'Phone Number',
        'preferred_address': 'Preferred Address',
        'payment_methods': 'Payment Methods',
        'save_changes': 'Save Changes',
        'profile_updated': 'Profile updated successfully!',
        'our_collection': 'Our Collection',
        'discover_premium': 'Discover our curated selection of premium essentials.',
        'all': 'All',
        'new_arrival': 'New Arrival',
        'quick_view': 'Quick View',
        'add_to_cart': 'Add to Cart',
        'no_products_found': 'no products found',
        'free_shipping': 'Free Shipping',
        'secure_payment': 'Secure Payment',
        'free_returns': 'Free Returns',
        'loyal_points': 'Loyal Points',
        'on_orders_over': 'On all orders over',
        'cash_card': 'Cash & Card Accepted',
        'return_policy': '30 days return policy',
        'earn_purchase': 'Earn on every purchase',
        'curated_selects': 'Curated selects for the digital era',
        'end_season_sale': 'End of Season Sale',
        'sale_desc': 'Up to 50% off on selected items. Don\'t miss out on the best deals of the year.',
        'shop_sale': 'Shop Sale',
        'new_product_entry': 'New Product Entry',
        'cancel_changes': 'Cancel Changes',
        'product_name_en': 'Product Name (English)',
        'product_name_ar': 'Product Name (Arabic)',
        'price': 'Price',
        'stock': 'Stock',
        'category': 'Category',
        'image_url': 'Image URL',
        'description_en': 'Description (English)',
        'description_ar': 'Description (Arabic)',
        'products_stock_control': 'Products Stock Control',
        'order_id': 'Order ID',
        'customer': 'Customer',
        'status': 'Status',
        'date': 'Date',
        'amount': 'Amount',
        'actions': 'Actions',
        'items': 'Items',
        'location': 'Location',
        'update_status': 'Update Status',
        'close': 'Close',
        'welcome_back': 'Welcome Back',
        'admin_dashboard': 'Admin Dashboard',
        'total_revenue': 'Total Revenue',
        'active_orders': 'Active Orders',
        'products_in_stock': 'Products in Stock',
        'total_customers': 'Total Customers',
        'recent_orders': 'Recent Orders',
        'hero_title_1': 'Summer Collection 2026',
        'hero_subtitle_1': 'Discover the latest trends in fashion.',
        'hero_cta_1': 'Shop Now',
        'hero_title_2': 'Elegance Redefined',
        'hero_subtitle_2': 'Premium quality for the modern lifestyle.',
        'hero_cta_2': 'View Collection',
        'hero_title_3': 'Urban Streetwear',
        'hero_subtitle_3': 'Express yourself with our unique styles.',
        'hero_cta_3': 'Explore',
        'live_transaction_hub': 'Live Transaction Hub',
        'search_placeholder_orders': 'Search ID, Customer, Email, or City...',
        'status_protocol': 'Status Protocol',
        'sort_sequence': 'Sort Sequence',
        'newest_first': 'Newest First',
        'oldest_first': 'Oldest First',
        'highest_value': 'Highest Value',
        'lowest_value': 'Lowest Value',
        'retrieving_protocols': 'Retrieving Protocols',
        'customer_entity': 'Customer Entity',
        'timestamp': 'Timestamp',
        'method': 'Method',
        'net_value': 'Net Value',
        'details': 'Details',
        'no_email': 'No email',
        'no_phone': 'No Phone',
        'protocols_no_match': 'No order protocols matching search',
        'order_details': 'Order Details',
        'transaction_total': 'Transaction Total',
        'customer_intelligence': 'Customer Intelligence',
        'logistics_deployment': 'Logistics & Deployment',
        'inventory_manifest': 'Inventory Manifest',
        'address': 'Address',
        'city_hub': 'City Hub',
        'qty': 'Qty',
        'unknown_asset': 'Unknown Asset',
        'no_manifest_data': 'No Manifest Data',
        'close_protocol_view': 'Close Protocol View',
        'collection_only': 'Collection Only',
        'confirm_delete': 'Are you sure you want to delete this product?',
        'currency_le': 'LE',
        'table_entry': 'Entry',
        'table_id': 'Identification',
        'table_division': 'Division',
        'table_value': 'Value',
        'table_units': 'Current Units',
        'table_operations': 'Operations',
        'order_id_prefix': 'ID:',
        'anonymous': 'Anonymous',
        'protocol_unknown': 'Protocol Unknown',
        'live_intelligence_overview': 'Live Intelligence Overview',
        'initializing_command_center': 'Initializing Command Center',
        'daily_sales': 'Daily Sales',
        'orders_count': 'Orders',
        'todays_transactions': 'Today\'s Transactions',
        'live': 'LIVE',
        'active_assets': 'Active Assets',
        'sku': 'SKU',
        'inventory_total': 'Inventory Total',
        'verified': 'Verified',
        'elite_customer': 'Elite Customer',
        'le_volume': 'LE Volume',
        'elite_performers': 'Elite Performers',
        'high_transaction_volume': 'High Transaction Volume',
        'lifetime_volume': 'Lifetime Volume',
        'no_data': 'No Data',
        'anonymous_user': 'Anonymous User',
        'legacy_user': 'Legacy User',
        'error': 'Error',
        'data_retrieval_failed': 'Data Retrieval Failed',
        'footer_tagline': 'Your premium destination for quality products. Experience excellence in every purchase.',
        'quick_links': 'Quick Links',
        'about_us': 'About Us',
        'customer_service': 'Customer Service',
        'my_account': 'My Account',
        'order_history': 'Order History',
        'faq': 'FAQ',
        'privacy_policy': 'Privacy Policy',
        'connect_with_us': 'Connect With Us',
        'all_rights_reserved': 'All rights reserved.',
        'terms': 'Terms',
        'cookies': 'Cookies',
        'rewards_system': 'Rewards System',
        'available_points': 'Available Points',
        'redeem_points': 'Redeem Points',
        'points_earned': 'Points Earned',
        'points_redeemed': 'Points Redeemed',
        'points_history': 'Points History',
        'earn_rate': 'Earn Rate',
        'redemption_rate': 'Redemption Rate',
        'apply_points': 'Apply Points',
        'points_applied': 'Points Applied',
        'discount_from_points': 'Discount from Points',
        'transaction_type': 'Transaction Type',
        'admin_adjustment': 'Admin Adjustment',
        'minimum_redemption': 'Minimum Redemption',
        'max_discount': 'Maximum Discount',
        'points_config': 'Points Configuration',
        'enable_rewards': 'Enable Rewards System',
        'points_per_currency': 'Points per LE',
        'points_value': 'Points Redemption Value',
        'recent_transactions': 'Recent Transactions',
        'no_transactions': 'No transactions yet',
        'earned': 'Earned',
        'redeemed': 'Redeemed',
        'adjust_points': 'Adjust Points',
        'add_points': 'Add Points',
        'deduct_points': 'Deduct Points',
        'points_adjustment': 'Points Adjustment',
        'enter_amount': 'Enter Amount',
        'reason': 'Reason',
        'apply_discount': 'Apply Discount',
        'maximum_points': 'Maximum Points',
        'points_will_save': 'You will save',
    },
    ar: {
        'home': 'الرئيسية',
        'products': 'المنتجات',
        'about': 'من نحن',
        'contact': 'تواصل معنا',
        'cart': 'عربة التسوق',
        'search': 'بحث',
        'admin': 'المسؤول',
        'login': 'تسجيل الدخول',
        'logout': 'تسجيل الخروج',
        'my_profile': 'ملفي الشخصي',
        'total': 'الإجمالي',
        'checkout': 'إتمام الشراء',
        'proceed_to_checkout': 'المتابعة لإتمام الشراء',
        'cash_notice': 'الدفع عند الاستلام فقط. دفع البطاقة قادم قريباً.',
        'trending': 'الأكثر مبيعاً',
        'view_all': 'مشاهدة الكل',
        'points': 'نقاط الولاء',
        'dashboard': 'لوحة التحكم',
        'orders': 'الطلبات',
        'my_orders': 'طلباتي',
        'account_settings': 'إعدادات الحساب',
        'full_name': 'الاسم بالكامل',
        'email_address': 'البريد الإلكتروني',
        'phone_number': 'رقم الهاتف',
        'preferred_address': 'العنوان المفضل',
        'payment_methods': 'طرق الدفع',
        'save_changes': 'حفظ التغييرات',
        'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
        'our_collection': 'تشكيلتنا',
        'discover_premium': 'اكتشف مجموعتنا المختارة من الأساسيات الفاخرة.',
        'all': 'الكل',
        'new_arrival': 'وصل حديثاً',
        'quick_view': 'نظرة سريعة',
        'add_to_cart': 'أضف للسلة',
        'no_products_found': 'لا توجد منتجات',
        'free_shipping': 'شحن مجاني',
        'secure_payment': 'دفع آمن',
        'free_returns': 'إرجاع مجاني',
        'loyal_points': 'نقاط الولاء',
        'on_orders_over': 'على جميع الطلبات فوق',
        'cash_card': 'نقبل الدفع نقداً وبالبطاقة',
        'return_policy': 'سياسة إرجاع خلال 30 يوم',
        'earn_purchase': 'اكسب النقاط مع كل عملية شراء',
        'curated_selects': 'مختارات مميزة للعصر الرقمي',
        'end_season_sale': 'تخفيضات نهاية الموسم',
        'sale_desc': 'خصم يصل إلى 50٪ على عناصر مختارة. لا تفوت أفضل صفقات العام.',
        'shop_sale': 'تسوق الآن',
        'new_product_entry': 'إضافة منتج جديد',
        'cancel_changes': 'إلغاء التغييرات',
        'product_name_en': 'اسم المنتج (إنجليزي)',
        'product_name_ar': 'اسم المنتج (عربي)',
        'price': 'السعر',
        'stock': 'المخزون',
        'category': 'الفئة',
        'image_url': 'رابط الصورة',
        'description_en': 'الوصف (إنجليزي)',
        'description_ar': 'الوصف (عربي)',
        'products_stock_control': 'مراقبة مخزون المنتجات',
        'order_id': 'رقم الطلب',
        'customer': 'العميل',
        'status': 'الحالة',
        'date': 'التاريخ',
        'amount': 'المبلغ',
        'actions': 'إجراءات',
        'items': 'العناصر',
        'location': 'الموقع',
        'update_status': 'تحديث الحالة',
        'close': 'إغلاق',
        'welcome_back': 'مرحباً بعودتك',
        'admin_dashboard': 'لوحة التحكم',
        'total_revenue': 'إجمالي الإيرادات',
        'active_orders': 'الطلبات النشطة',
        'products_in_stock': 'المنتجات في المخزون',
        'total_customers': 'إجمالي العملاء',
        'recent_orders': 'أحدث الطلبات',
        'hero_title_1': 'عروض صيف 2026',
        'hero_subtitle_1': 'اكتشف أحدث صيحات الموضة.',
        'hero_cta_1': 'تسوق الآن',
        'hero_title_2': 'أناقة بلا حدود',
        'hero_subtitle_2': 'جودة عالية لأسلوب حياة عصري.',
        'hero_cta_2': 'شاهد التشكيلة',
        'hero_title_3': 'أزياء الشارع',
        'hero_subtitle_3': 'عبر عن نفسك بأسلوبنا الفريد.',
        'hero_cta_3': 'استكشف',
        'live_transaction_hub': 'مركز العمليات المباشر',
        'search_placeholder_orders': 'ابحث بالرقم، العميل، البريد، أو المدينة...',
        'status_protocol': 'بروتوكول الحالة',
        'sort_sequence': 'تسلسل الفرز',
        'newest_first': 'الأحدث أولاً',
        'oldest_first': 'الأقدم أولاً',
        'highest_value': 'الأعلى قيمة',
        'lowest_value': 'الأقل قيمة',
        'retrieving_protocols': 'جاري استرجاع البروتوكولات',
        'customer_entity': 'كيان العميل',
        'timestamp': 'الطابع الزمني',
        'method': 'الطريقة',
        'net_value': 'القيمة الصافية',
        'details': 'التفاصيل',
        'no_email': 'لا يوجد بريد',
        'no_phone': 'لا يوجد هاتف',
        'protocols_no_match': 'لا توجد بروتوكولات طلب مطابقة',
        'order_details': 'تفاصيل الطلب',
        'transaction_total': 'إجمالي المعاملة',
        'customer_intelligence': 'استخبارات العميل',
        'logistics_deployment': 'اللوجستيات والنشر',
        'inventory_manifest': 'بيان المخزون',
        'address': 'العنوان',
        'city_hub': 'مركز المدينة',
        'qty': 'الكمية',
        'unknown_asset': 'أصل غير معروف',
        'no_manifest_data': 'لا توجد بيانات',
        'close_protocol_view': 'إغلاق عرض البروتوكول',
        'collection_only': 'استلام فقط',
        'confirm_delete': 'هل أنت متأكد أنك تريد حذف هذا المنتج؟',
        'currency_le': 'ج.م',
        'table_entry': 'الإدخال',
        'table_id': 'التعريف',
        'table_division': 'القسم',
        'table_value': 'القيمة',
        'table_units': 'الوحدات الحالية',
        'table_operations': 'العمليات',
        'order_id_prefix': 'رقم:',
        'anonymous': 'مجهول',
        'protocol_unknown': 'البروتوكول غير معروف',
        'live_intelligence_overview': 'نظرة عامة على الذكاء المباشر',
        'initializing_command_center': 'تهيئة مركز القيادة',
        'daily_sales': 'المبيعات اليومية',
        'orders_count': 'طلبات',
        'todays_transactions': 'معاملات اليوم',
        'live': 'مباشر',
        'active_assets': 'الأصول النشطة',
        'sku': 'وحدة حفظ المخزون',
        'inventory_total': 'إجمالي المخزون',
        'verified': 'مُتحقق منه',
        'elite_customer': 'عميل نخبة',
        'le_volume': 'حجم ج.م',
        'elite_performers': 'المتفوقون',
        'high_transaction_volume': 'حجم معاملات عالي',
        'lifetime_volume': 'الحجم الكلي',
        'no_data': 'لا توجد بيانات',
        'anonymous_user': 'مستخدم مجهول',
        'legacy_user': 'مستخدم قديم',
        'error': 'خطأ',
        'data_retrieval_failed': 'فشل استرجاع البيانات',
        'footer_tagline': 'وجهتك المميزة للمنتجات عالية الجودة. استمتع بالتميز في كل عملية شراء.',
        'quick_links': 'روابط سريعة',
        'about_us': 'من نحن',
        'customer_service': 'خدمة العملاء',
        'my_account': 'حسابي',
        'order_history': 'سجل الطلبات',
        'faq': 'الأسئلة الشائعة',
        'privacy_policy': 'سياسة الخصوصية',
        'connect_with_us': 'تواصل معنا',
        'all_rights_reserved': 'جميع الحقوق محفوظة.',
        'terms': 'الشروط',
        'cookies': 'ملفات تعريف الارتباط',
        'rewards_system': 'نظام المكافآت',
        'available_points': 'النقاط المتاحة',
        'redeem_points': 'استبدال النقاط',
        'points_earned': 'النقاط المكتسبة',
        'points_redeemed': 'النقاط المستردة',
        'points_history': 'سجل النقاط',
        'earn_rate': 'معدل الكسب',
        'redemption_rate': 'معدل الاستبدال',
        'apply_points': 'تطبيق النقاط',
        'points_applied': 'النقاط المطبقة',
        'discount_from_points': 'الخصم من النقاط',
        'transaction_type': 'نوع المعاملة',
        'admin_adjustment': 'تعديل إداري',
        'minimum_redemption': 'الحد الأدنى للاستبدال',
        'max_discount': 'الحد الأقصى للخصم',
        'points_config': 'إعدادات النقاط',
        'enable_rewards': 'تفعيل نظام المكافآت',
        'points_per_currency': 'النقاط لكل جنيه',
        'points_value': 'قيمة استبدال النقاط',
        'recent_transactions': 'المعاملات الأخيرة',
        'no_transactions': 'لا توجد معاملات بعد',
        'earned': 'مكتسب',
        'redeemed': 'مستبدل',
        'adjust_points': 'تعديل النقاط',
        'add_points': 'إضافة نقاط',
        'deduct_points': 'خصم نقاط',
        'points_adjustment': 'تعديل النقاط',
        'enter_amount': 'أدخل المبلغ',
        'reason': 'السبب',
        'apply_discount': 'تطبيق الخصم',
        'maximum_points': 'الحد الأقصى للنقاط',
        'points_will_save': 'ستوفر',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        const storedLang = localStorage.getItem('language') as Language;
        if (storedLang) {
            setLanguage(storedLang);
            document.documentElement.dir = storedLang === 'ar' ? 'rtl' : 'ltr';
            document.documentElement.lang = storedLang;
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, dir: language === 'ar' ? 'rtl' : 'ltr' }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
